[project]
name = "robotics-manipulation-russ"
version = "0.1.0"
description = "A project for robotic manipulation based on Drake"
readme = "README.md"
requires-python = ">=3.10, <=3.11"
dependencies = [
    "numpy",
    "drake>=1.0.0, <=1.44.0",
    "matplotlib",
    "ipykernel",
    "manipulation",
    "nbformat",
    "gradescope_utils",
    "nbconvert",
    "timeout_decorator",
    "trimesh",
    "rtree",
    "shapely",
    "mapbox-earcut",
    "manifold3d",
    "triangle",
    "coacd",
    "scipy",
    "PyMCubes",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
